name: playground

packages:
  - packages/*

repository: https://github.com/KoheiKanagu/playground

command:
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: |
        melos run pub:get

sdkPath: .fvm/versions/beta
