name: playground

packages:
  - packages/*

repository: https://github.com/KoheiKanagu/playground

command:
  version:
    branch: main
    linkToCommits: true
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: |
        melos run pub:get
