name: playground

packages:
  - packages/*

repository: https://github.com/KoheiKanagu/playground

command:
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: |
        melos run pub:get

scripts:
  pub:get:
    run: |
      dart pub get
      melos exec -- "flutter pub get"

sdkPath: .fvm/versions/beta
