name: example1
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.0-0
  flutter: ^3.17.0-0

dependencies:
  adaptive_dialog: ^2.0.0
  budoux_dart: ^1.2.0
  clock: ^1.1.1
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.0
  collection: ^1.18.0
  core:
    path: ../core
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  firebase_analytics: ^10.8.0
  firebase_app_check: ^0.2.1+5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+5
  firebase_remote_config: ^4.3.8
  firebase_ui_auth: ^1.12.1
  firebase_ui_oauth_apple: ^1.2.17
  firebase_ui_oauth_google: ^1.2.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.1.0
  hooks_riverpod: ^2.4.10
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  permission_handler: ^11.2.0
  riverpod_annotation: ^2.3.4
  roggle: ^0.4.2+1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  alchemist: ^0.7.0
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  flutter_gen_runner: ^5.4.0
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  test: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - packages/budoux_dart/models/ja.json
# flutter_native_splash:
#   color: "#FAFDFD" # lightColorScheme.background
#   image: "assets/splash_icon.png"
#   color_dark: "#191C1D" # darkColorScheme.background
#   image_dark: "assets/splash_icon_dark.png"
#   android_12:
#     image: "assets/splash_icon.png"
#     color: "#FAFDFD" # lightColorScheme.background
#     image_dark: "assets/splash_icon_dark.png"
#     color_dark: "#191C1D" # darkColorScheme.background
#   android: true
#   ios: true
#   fullscreen: true
