name: client_app Bug Report
description: File a bug report for client_app
labels: ["bug", "triage", "client_app"]
assignees:
  - KoheiKanagu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? You can also attach videos or screenshots.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: latest
      value: latest
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - iOS
        - Android
        - macOS
  - type: input
    id: os-version
    attributes:
      label: What version of the OS are you running?
      description: If you're not sure, you can find this in the settings.
  - type: dropdown
    id: severity
    attributes:
      label: How severe is the bug?
      options:
        - Critical
        - Major
        - Minor
        - Trivial
  - type: input
    id: datetime
    attributes:
      label: When did you encounter the bug?
      description: Please tell us the approximate time. We will look for detailed logs in Firebase Crashlytics.
      placeholder: YYYY-MM-DD HH:MM:SS
