name: Auto Merge

on:
  workflow_run:
    workflows:
      - Pull Requests
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      contains(github.event.workflow_run.pull_requests[0].labels.*.name, 'auto_merge')
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App token
        uses: tibdex/github-app-token@v1.8.0
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload))

      - name: Merge
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "gh pr merge ${{ github.event.workflow_run.pull_requests[0].number }} --squash --delete-branch"
