name: Auto Merge

on:
  workflow_run:
    workflows:
      - Pull Requests
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub App token
        uses: tibdex/github-app-token@v1.8.0
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - run: |
          pr_number=${{ github.event.workflow_run.pull_requests[0].number }}
          echo "pr_number=$pr_number" >> $$GITHUB_ENV

          pr_labels=$(gh pr view $pr_number --json labels)
          echo "pr_labels=$pr_labels" >> $$GITHUB_ENV

          echo "$pr_labels"
        id: labels
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Merge
        if: contains(steps.labels.outputs.pr_labels.labels.*.name, 'merge')
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh pr view ${{ steps.labels.outputs.pr_number }}
          echo "gh pr merge ${{ steps.labels.outputs.pr_number }} --squash --delete-branch"
