name: Auto Merge

on:
  workflow_run:
    workflows:
      - Pull Requests
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GitHub App token
        uses: tibdex/github-app-token@v1.9.0
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get PR number and labels
        id: labels
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          pr_number=${{ github.event.workflow_run.pull_requests[0].number }}
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"

          pr_labels=$(gh pr view $pr_number --json labels)
          echo "pr_labels=$pr_labels" >> "$GITHUB_OUTPUT"

      - name: Auto merge
        if: contains(fromJson(steps.labels.outputs.pr_labels).labels.*.name, 'auto_merge')
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh pr merge ${{ steps.labels.outputs.pr_number }} --squash --delete-branch
