name: Pull Requests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "firebase/**"
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: KoheiKanagu/composite-actions/setup-flutter@main

      ### Build ###
      - name: Build
        run: |
          echo "Hello World!"

      - run: which flutter
      - run: which dart
      - run: melos exec -- which flutter
      - run: melos exec -- which dart
      - run: melos exec -- flutter doctor