name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event) }}

  # check-pr-title:
  #   if: github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   permissions:
  #     statuses: write
  #   steps:
  #     - uses: aslafy-z/conventional-pr-title-action@v3
  #       if: github.actor != 'dependabot[bot]'
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
