name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo '${{ github.event.pull_request.title }}'
      - run: echo '${{ github.event.pull_request.head.ref }}'

  check-pr-title:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.pull_request.title }}'
